### ISSUE TITLE
Data Download Problem

### ISSUE THREAD

**Issue by skotey** [oncescuandreea/QuerYD_downloader#1]
When attempting to download the full dataset I receive this error after the 9th video. The test videos download ok. Any advice as to what is wrong?

`Traceback (most recent call last):
  File "download_queryd.py", line 233, in <module>
    main()
  File "download_queryd.py", line 221, in main
    download_videos(args.video_dir, args.txt_file,
  File "download_queryd.py", line 97, in download_videos
    pool_func(**kwarg)
  File "download_queryd.py", line 41, in download_one_video
    video.download(video_dir, filename=video_name)
AttributeError: 'NoneType' object has no attribute 'download'
`

**Comment by oncescuandreea** [comment]
Hi, I think the issue can be solved if you install the latest version of pytube. I have updated the README file with the command line installing pytube from the github repo. Thanks!
