### ISSUE TITLE
Video Features

### ISSUE THREAD

**Issue by skotey** [oncescuandreea/QuerYD_downloader#2]
Are you planning on releasing the extracted features for the videos? If yes, is there a time frame for that? Thanks!

**Comment by oncescuandreea** [comment]
Hi, yes. The collaborative experts repo should be updated in the next few weeks. Until then the link to the features can be found in the updated README file. Thanks!
http://www.robots.ox.ac.uk/~vgg/research/collaborative-experts/data/features-v2/QuerYD-experts.tar.gz
http://www.robots.ox.ac.uk/~vgg/research/collaborative-experts/data/features-v2/QuerYDSegments-experts.tar.gz
