### ISSUE TITLE
Can you check the file for downloading v2?

### ISSUE THREAD

**Issue by yaseryacoob** [oncescuandreea/QuerYD_downloader#3]
The link (for v2) is not pointing  anywhere and breaks when I try it. Unless v1 has everything? if so why have v2.

thanks

**Comment by oncescuandreea** [comment]
Hi, sorry for this issue, thanks for bringing it up. I have now updated the v2 file. The v2 file contains the updated list of videos. Let me know if there are any problems. Thanks!
