### ISSUE TITLE
Timestamp Data

### ISSUE THREAD

**Issue by benjaminklein** [oncescuandreea/QuerYD_downloader#4]
Hi, Looking for the timestamp data I see the following:>>> data['video-KAyVk_sH42k']
[[63.3027940629425, 63.3027940629425], [41.683449186920164, 45.6087825202535], [132.08479804196168, 132.08479804196168], [0, 11.264], [190.805176917984, 195.32784358465068], [18.880897, 18.880897], [99.51919, 99.51919], [153.01214398283386, 153.01214398283386], [69.0509181373291, 80.22958480399578], [195.429788, 195.429788]]

It looks for many of them - the start time and the end time are the same. This is true for multiple videos I tried. Can you maybe advise about this?

Thank you

**Comment by oncescuandreea** [comment]
Hi Benjamin,

Thanks for the question. The timestamp data contains all start and end times for all available audio descriptions.
Essentially, for each video there are multiple audio description files in the form of .wav files. These files can be of 3 types:
- In-sync or localised, where start time is different from end_time (english descriptions)
- Coarsely localised, where the video has been paused when the audio description was recorded, where start time = end time (english descriptions)
- Non-english localised or coarsely localised audio descriptions.

In our localisation experiments we have only used the 1st type of descriptions. So, for the QuerYDSegments splits, the video segments and their corresponding audio descriptions found in the train/val/test data have a different start and end times. These splits can be found by downloading the QuerYDSegments features and splits as shown at the end of the README.

To check if indeed what I said if correct, you can find the corresponding audio-description .wav file name to the timestamps above here: https://www.robots.ox.ac.uk/~vgg/data/queryd/assets/data/ordered_captions_combined_filtered.pkl.

I hope this helps!

**Comment by benjaminklein** [comment]
Thank you for the explanation!
